version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: registration
      MYSQL_USER: reguser
      MYSQL_PASSWORD: regpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    environment:
      PHP_UPLOAD_MAX_FILESIZE: 10M
      PHP_POST_MAX_SIZE: 10M
      PHP_OPCACHE_ENABLE: 0
      PHP_ERROR_REPORTING: E_ALL
      PHP_DISPLAY_ERRORS: 1
      PHP_DISPLAY_STARTUP_ERRORS: 1
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: reguser
      PMA_PASSWORD: regpass
      UPLOAD_LIMIT: 100M
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
