version: "3.8"

services:
  db:
    image: mysql:8.0
    env_file:
      - ./src/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./src/.env
    environment:
      PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE}
      PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE}
      PHP_OPCACHE_ENABLE: ${PHP_OPCACHE_ENABLE}
      PHP_ERROR_REPORTING: ${PHP_ERROR_REPORTING}
      PHP_DISPLAY_ERRORS: ${PHP_DISPLAY_ERRORS}
      PHP_DISPLAY_STARTUP_ERRORS: ${PHP_DISPLAY_STARTUP_ERRORS}
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: reguser
      PMA_PASSWORD: regpass
      UPLOAD_LIMIT: 100M
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
